ARG version
FROM almalinux:${version:-9}
ARG COURSE=Docker
ARG TRAINER=Sivakumar
ENV Duration=120hrs
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER} Duration:${Duration} "
CMD [ "sleep","100" ]