ARG version
FROM almalinux:${version:-9}
ARG COURSE=Docker
ARG TRAINER=Sivakumar
ARG Duration=120hrs 
ENV Duration=${Duration}
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER} Duration:${Duration} "
CMD [ "sleep","100" ]